# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-11-27 23:57
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Graph',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('graph_type', models.CharField(max_length=200)),
                ('graph_description', models.CharField(max_length=200)),
                ('graph_data', models.TextField()),
            ],
        ),
    ]
