# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-12-12 23:11
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
        ('tweet_display', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='graph',
            name='open_humans_member',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='users.OpenHumansMember'),
            preserve_default=False,
        ),
    ]
