# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-12-13 22:55
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tweet_display', '0002_graph_open_humans_member'),
    ]

    operations = [
        migrations.AlterField(
            model_name='graph',
            name='open_humans_member',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='users.OpenHumansMember'),
        ),
    ]
